# Default values for http-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ""
  name: http-server
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

persistence:
  http:
    accessMode: ReadWriteOnce
    size: 10Mi

nameOverride: ""
fullnameOverride: "http-server"

podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deployment:
  port: 8000

service:
  type: ClusterIP
  port: 80

servicemonitor:
  enabled: false
  port: 8001

nodeSelector: {}
