kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "http-server.fullname" . }}
  labels:
    app: "{{ template "http-server.fullname" . }}"
    chart: "{{ template "http-server.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.http.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.http.size | quote }}