apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-server.fullname" . }}
  labels:
    {{- include "http-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
  selector:
    {{- include "http-server.serviceMonitorLabels" . | nindent 4 }}
